---
- hosts: esxi_server
  vars:
    delay: 4
    count: 43200
    script_path: "/esxtop"
  tasks:
    - name: start esxtop script
      command: 
          "{{script_path}}/rackhd_esxtop_csv_collector.py -n {{count}} -d {{delay}}"
      register: collect_job
      async: "{{count*delay+10|int}}"
      poll: 0
      when: esxtop

- hosts: test_machine
  vars:
    benchmark_path: "{{inventory_dir}}/RackHD/test/"
  tasks:
    - name: start benchmark 
      shell: 
          virtualenv .venv; source .venv/bin/activate;pip install -r requirements.txt;python benchmark.py start
      args:
          chdir: "{{benchmark_path}}"
          executable: /bin/bash
      ignore_errors: yes
      become: False
      when: benchmark

- hosts: rackhd
  tasks:
      - name: clear old logs
        shell: rm /var/log/upstart/*
        ignore_errors: yes
        become: True
        when: log

