---
- hosts: esxi_server
  vars_files:
    - vars/start.yml

  tasks:
    - name: start esxtop script
      command: "{{ esxi_remote_path }}/rackhd_esxtop_csv_collector.py -n {{ esxi_count }} -d {{ esxi_delay }}"
      register: collect_job
      async: "{{ esxi_count*esxi_delay+10|int }}"
      poll: 0
      when: esxtop

- hosts: test_machine
  vars_files:
    - vars/start.yml

  tasks:
    - name: start benchmark
      shell: virtualenv .venv; source .venv/bin/activate;pip install -r requirements.txt;pip install markupsafe;python benchmark.py --start
      args:
          chdir: "{{ benchmark_path }}"
          executable: /bin/bash
      ignore_errors: yes
      become: False
      when: benchmark

- hosts: rackhd

  tasks:
      - name: get rackhd ubuntu version
        shell: lsb_release -a | grep Release | awk '{print $2}' | awk -F '.' '{print $1}'
        register: release
        ignore_errors: yes
        become: True
        when: log

      - name: clear old logs
        shell: rm /var/log/upstart/*
        ignore_errors: yes
        become: True
        when: log and (release == "14")

      - name: clear old logs
        shell: rm /var/log/rackhd/*
        ignore_errors: yes
        become: True
        when: log and (release == "16")
