---
- hosts: esxi_server
  vars:
    script_path: "/esxtop/parser"
    logstash_path: "{{inventory_dir}}/elk/logstash/rackhd_esxtop.logstash"
    kibana_path: "{{inventory_dir}}/elk/kibana/rackhd_esxtop_kibana.json"
    csv_path: "/tmp/rackhd_esxtop.csv"
  tasks:
    - name: stop esxtop script
      command: ./kill_pid_esxi.sh esxtop
      args:
          chdir: "{{script_path}}"
      ignore_errors: yes
    - name: copy back esxtop  file
      fetch: src={{script_path}}/rackhd_esxtop.logstash dest={{logstash_path}} flat=yes 
      ignore_errors: yes
    - name: copy back esxtop kibana configure file
      fetch: src={{script_path}}/rackhd_esxtop_kibana.json dest={{kibana_path}} flat=yes
      ignore_errors: yes
    - name: copy back esxtop csv file
      fetch: src={{script_path}}/rackhd_esxtop.csv dest=/tmp/rackhd_esxtop.csv flat=yes
      ignore_errors: yes

- hosts: test_machine
  vars:
    script_path: "{{inventory_dir}}/benchmark_elk"
    benchmark_tool_path: "{{inventory_dir}}/RackHD/test/"
  tasks:
    - name: stop benchmark 
      shell: virtualenv .venv; source .venv/bin/activate;python benchmark.py --stop
      args:
          chdir: "{{benchmark_tool_path}}"
          executable: /bin/bash
      ignore_errors: yes
      become: False 
    - name: get latest benchmark log file
      shell: virtualenv .venv > /dev/null; source .venv/bin/activate > /dev/null;python benchmark.py --getdir 
      register: benchmark_log_path
      args:
          chdir: "{{benchmark_tool_path}}"
          executable: /bin/bash
      become: False 
    - name: generate benchmark logstash file
      command: "{{script_path}}/generate_benchmark_logstash.py --path {{benchmark_log_path.stdout}}/data" 

- hosts: rackhd
  vars:
    log_path: "/var/log"
  tasks:
    - name: pack RackHD log files
      shell: tar -cvf upstart.tar upstart/ 
      args:
          chdir: "{{log_path}}"
      become: True
    - name: copy RackHD log files
      fetch: src={{log_path}}/upstart.tar
             dest={{inventory_dir}}
             flat=yes

- hosts: test_machine
  tasks:
    - name: unpack rackhd log from .tar packages
      shell: tar -xvf upstart.tar; rm upstart.tar
      register: unpack_flag
      args:
          chdir: "{{inventory_dir}}"
      ignore_errors: yes
    - name: unpack rackhd log from .gz packages
      shell: gzip -d *.gz
      args:
          chdir: "{{inventory_dir}}/upstart"
      ignore_errors: yes



