---
- hosts: test_machine

  tasks:
    - name: kill previous logstash processes
      shell: "{{ inventory_dir }}/files/kill_pid_linux.sh logstash"
      become: yes

    - name: remove previous data logs
      shell: rm -rf {{ data_log_path }}/*; rm {{ logstash_conf_path }}/*.logstash; rm -rf {{ kibana_conf_path }}/*.kibana

- hosts: esxi_server

  tasks:
    - name: stop esxtop script
      command: "{{ esxtop_exec_path }}/kill_pid_esxi.sh esxtop"
      ignore_errors: yes
      when: esxtop

    - name: find esxtop logstash config file
      shell: ls {{ esxtop_exec_path }}/*.logstash
      register: fetch_file
      when: esxtop

    - name: copy back esxtop logstash file
      fetch:
          src={{ fetch_file.stdout }}
          dest={{ logstash_conf_path }}
          flat=yes
          fail_on_missing=yes
      ignore_errors: yes
      when: esxtop

    - name: find esxtop kibana config file
      shell: ls {{ esxtop_exec_path }}/*.kibana
      register: fetch_file
      when: esxtop

    - name: copy back esxtop kibana configure file
      fetch:
          src={{ fetch_file.stdout }}
          dest={{ kibana_conf_path }}
          flat=yes
          fail_on_missing=yes
      ignore_errors: yes
      when: esxtop

    - name: find esxtop csv file
      shell: ls {{ esxtop_exec_path }}/*.csv
      register: fetch_file
      when: esxtop

    - name: copy back esxtop csv file
      fetch:
          src={{ fetch_file.stdout }}
          dest={{ data_log_path }}
          flat=yes
          fail_on_missing=yes
      ignore_errors: yes
      when: esxtop

- hosts: rackhd

  tasks:
    - name: get rackhd ubuntu version
      shell: lsb_release -a | grep Release | awk '{print $2}' | awk -F '.' '{print $1}'
      register: release
      #ignore_errors: yes
      become: True
      when: rackhdlog

    - name: pack RackHD log files
      shell: tar zcvf upstart.tar.gz upstart/
      args:
          chdir: "{{ rackhdlog_exec_path }}"
      become: yes
      when: rackhdlog and (release.stdout == "14")

    - name: pack RackHD log files
      shell: tar zcvf upstart.tar.gz rackhd/
      args:
          chdir: "{{ rackhdlog_exec_path }}"
      become: yes
      when: rackhdlog and (release.stdout == "16")

    - name: copy RackHD log files
      fetch:
          src={{ rackhdlog_exec_path }}/upstart.tar.gz
          dest={{ data_log_path }}
          flat=yes
          mode=777
      when: rackhdlog

- hosts: test_machine

  tasks:
    ## Prepare benchmark logs and logstash configure file
    - name: stop benchmark
      shell:
          virtualenv .venv; source .venv/bin/activate;python benchmark.py --stop
      args:
          chdir: "{{ benchmark_exec_path }}"
          executable: /bin/bash
      ignore_errors: yes
      when: benchmark

    ## Prepare RackHD logs
    - name: unpack rackhd log from .tar.gz packages
      shell: tar zxvf upstart.tar.gz; rm upstart.tar.gz
      register: unpack_flag
      args:
          chdir: "{{ data_log_path }}"
      ignore_errors: yes
      when: rackhdlog

    ## Copy ELK config files into corresponding tool
    - name: find benchmark logstash config file
      shell: ls {{ benchmark_elk_script_path }}/*.logstash
      register: fetch_file
      when: benchmark

    - name: copy benchmark logstash file to correct place
      copy:
          src={{ fetch_file.stdout }}
          dest={{ logstash_conf_path }}
      when: benchmark

    - name: find benchmark kibana config file
      shell: ls {{ benchmark_elk_script_path }}/*.kibana
      register: fetch_file
      when: benchmark

    - name: copy benchmark kibana file to correct place
      copy:
          src={{ fetch_file.stdout }}
          dest={{ kibana_conf_path }}
      when: benchmark

    - name: find rackhdlog logstash config file
      shell: ls {{ rackhdlog_elk_script_path }}/*.logstash
      register: fetch_file
      when: rackhdlog

    - name: copy rackhdlog logstash file to correct place
      copy:
          src={{ fetch_file.stdout }}
          dest={{ logstash_conf_path }}
      when: rackhdlog

    - name: find rackhdlog kibana config file
      shell: ls {{ rackhdlog_elk_script_path }}/*.kibana
      register: fetch_file
      when: rackhdlog

    - name: copy rackhdlog kibana file to correct place
      copy:
          src={{ fetch_file.stdout }}
          dest={{ kibana_conf_path }}
      when: rackhdlog

    - name: find logstash config file
      shell: ls *.logstash
      args:
          chdir: "{{ logstash_conf_path }}"
      register: conf_file

    - name: initiate logstash
      shell: ./bin/logstash -f {{ logstash_conf_path }}/{{ item }} >> logs/logstash.log &
      #shell: ./bin/logstash -f config/ > logstash.log &
      args:
          chdir: "{{ elk_path }}/logstash"
      with_items:
          "{{ conf_file.stdout_lines }}"

    #- pause: seconds=15
    ## Configure kibana
    - name: Configure kibana
      command: python {{ inventory_dir }}/files/set_kibana_config.py
      register: result
      args:
          chdir: "{{ inventory_dir }}"
      #ignore_errors: yes
      become: yes
      until: result.rc == 0
      retries: 5
      delay: 15
